spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tmdwh5@gmail.com
    password: my-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
